### ISSUE TITLE
how to query _id with timestamp

### ISSUE THREAD

**Issue by randyh0329** [hakobera/embulk-input-mongodb#29]
I want to query _id field with timestamp, but hit 'query' parameter error.

following is my yaml:

```
in:
  type: mongodb
  hosts:
  - {host: 192.168.99.100, port: 32768}
  database: test
  collection: "restaurants"
  query: '{ "_id": { $gt: ObjectId(Math.floor((new Date("2015/4/4"))/1000).toString(16) + "0000000000000000") } }'
```

```
Error: Invalid JSON string was given for 'query' parameter. [{ "_id": { $gt: ObjectId(Math.floor((new Date("2015/4/4"))/1000).toString(16) + "0000000000000000") } }]
```

Thanks for the helping.
